/**
 * Stable, machine-switchable error codes (PDD §31). Codes are wire format:
 * renaming one is a breaking change to every process boundary at once.
 */
export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  FILE_BUSY: 'FILE_BUSY',
  NOT_A_FILE: 'NOT_A_FILE',
  LIMIT_REACHED: 'LIMIT_REACHED',
  EXPORT_IN_PROGRESS: 'EXPORT_IN_PROGRESS',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  NOT_READY: 'NOT_READY',
  INVALID_CONFIG: 'INVALID_CONFIG',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  AGENT_UNAVAILABLE: 'AGENT_UNAVAILABLE',
  MALFORMED_RESPONSE: 'MALFORMED_RESPONSE',
  INSUFFICIENT_SPACE: 'INSUFFICIENT_SPACE',
  UNSUPPORTED_OPERATION: 'UNSUPPORTED_OPERATION',
  INTERNAL: 'INTERNAL',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * HTTP status the agent serves for each code. Client-side-only codes
 * (REQUEST_TIMEOUT, AGENT_UNAVAILABLE, MALFORMED_RESPONSE) never appear on the
 * wire from the agent and are absent here (PDD §31 table).
 */
export const ERROR_HTTP_STATUS: Partial<Record<ErrorCode, number>> = {
  AUTH_REQUIRED: 401,
  AUTH_INVALID: 401,
  VALIDATION_FAILED: 400,
  NOT_FOUND: 404,
  FILE_NOT_FOUND: 404,
  PERMISSION_DENIED: 403,
  FILE_BUSY: 423,
  NOT_A_FILE: 422,
  LIMIT_REACHED: 409,
  EXPORT_IN_PROGRESS: 409,
  PAYLOAD_TOO_LARGE: 413,
  NOT_READY: 503,
  INVALID_CONFIG: 400,
  INSUFFICIENT_SPACE: 507,
  UNSUPPORTED_OPERATION: 501,
  INTERNAL: 500,
} as const;
